### ISSUE TITLE
Update Github actions

### ISSUE THREAD

**Issue by chris-bateman** [logspace-ai/langflow#1415]
Updating Github actions due to node EOL.

I am happy to update these in one of two ways - 

1. Manually with a PR per action to test each workflow gradually.  **Or**
2. Enable dependabot for Github-Actions with reasonable settings.  Weekly/Monthly checks.  This will reduce dependabot spam :)

- [x] actions/checkout@v4 #1419 
- [x] actions/cache@v4 #1421 
- [x] github/codeql-action (Including sub actions) to @v3 ([Release notes](https://github.com/github/codeql-action/tree/main?tab=readme-ov-file#supported-versions-of-the-codeql-action)) #1420 
- [x] actions/setup-node@v4 #1423 
- [x] actions/setup-python@v5 #1422

**Comment by ogabrielluiz** [comment]
Hey @chris-bateman 

I think the dependabot can be quite useful.

Will it update the actions too?

**Comment by chris-bateman** [comment]
> Hey @chris-bateman 
> 
> I think the dependabot can be quite useful.
> 
> Will it update the actions too?

Yep it will only update actions in this case.
